server:
  port: 8080

spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.llm.gateway.dal.model
  mapper-locations: classpath*:com.llm.gateway.dal.mapper

logging:
  config: classpath:logback-spring.xml

jwt:
  secret: 2026-advanceWithAI-LLMGateway-QY
  # 86400 = 1天
  expirationSeconds: 86400
